version: '2.4'

services:
  react_native_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'